baseurl = "http://misfra.me/"
title = "Misframe"
author = "Preetam Jinka"
copyright = "Copyright &copy; Preetam Jinka"
theme = "misframe"
canonifyurls = false
paginate = 10
rsslink = "feed"
DisqusShortname = "preetamjinka"

[params]
  DateForm = "Mon, Jan 2, 2006"
  RSSlink = "feed"
  RSSUri = "feed"
  twitter = "PreetamJinka"
  github = "PreetamJinka"
  linkedin = "preetamjinka"
  facebook = "PreetamJinka"
  ga_api_key = "UA-37425054-1"
